#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  default:
        - step:
            name: Build and Test
            caches:
              - dotnetcore
            script:
              - dotnet restore
              - dotnet build SampleCICDapplication/SampleCICDapplication.csproj
              - dotnet test SampleCICDUnitTest/SampleCICDUnitTest.csproj
              
